# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Amanda's Website
email: 
description: A Website For My Class Assignments
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aehaney.github.io" # the base hostname & protocol for your site
twitter_username: amanda_haney
github_username:  aehaney

# Build settings
markdown: kramdown
